export const siteConfig = {
  name: "Klaten International Minisoccer",
  title: "Klaten International Minisoccer | Sewa Lapangan Mini Soccer di Klaten",
  description:
    "Sewa lapangan mini soccer di Klaten di Klaten International Minisoccer, Karanganom Klaten Utara. Booking lapangan Klaten online, harga sekitar Rp 214.000 - 750.000, jadwal per jam 06.00–23.00. Telp +62 812 3456 7890.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://klatenminisoccer.web.id",
  locale: "id_ID",
  keywords: [
    "klaten international minisoccer",
    "lapangan di klaten",
    "sewa lapangan klaten",
    "booking lapangan klaten",
    "lapangan mini soccer klaten",
    "mini soccer klaten",
    "futsal klaten",
    "sewa lapangan mini soccer klaten",
    "lapangan klaten utara",
    "klaten international minisoccer",
    // Kata kunci tambahan untuk SEO (dari riset)
    "lapangan mini soccer klaten hargaterjang",
    "sewa lapangan klaten per jam",
    "tempat sewa lapangan klaten",
    "lapangan futsal klaten",
    "booking lapangan klaten online",
    "lapangan klaten utara",
    "harga lapangan per jam klaten",
    "tempat sewa lapangan murah klaten",
    "lapangan mini soccer di klaten",
    "klaten international minisoccer",
  ],
  openGraphImage: "/kim-logo.png",
  phone: "+62 857 744 40016",
  email: "admin@dev.klatenminisoccer.web.id",
  instagram: "https://www.instagram.com/kim.soccerfield/",
  address: "Jl. Desan Karanganom, Karanganom, Kec. Klaten Utara, Kabupaten Klaten, Jawa Tengah 57438",
  hours: "06.00–23.00 Setiap hari",
  navItems: [
    { href: "/", label: "Beranda" },
    { href: "/book", label: "Booking Lapangan" },
    { href: "/booking-history", label: "Riwayat" },
  ],
};
