export const siteConfig = {
  name: "Klaten International Minisoccer",
  title: "Klaten International Minisoccer | Sewa Lapangan Mini Soccer Klaten",
  description:
    "Klaten International Minisoccer — lapangan mini soccer premium di Klaten Utara. Booking online, harga Rp 214.000–750.000, buka 06.00–23.00 setiap hari.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://klatenminisoccer.web.id",
  locale: "id_ID",
  keywords: [
    "klaten international minisoccer",
    "lapangan di klaten",
    "sewa lapangan klaten",
    "booking lapangan klaten",
    "lapangan mini soccer klaten",
    "mini soccer klaten",
    "futsal klaten",
    "sewa lapangan mini soccer klaten",
    "lapangan klaten utara",
    "sewa lapangan klaten per jam",
    "tempat sewa lapangan klaten",
    "lapangan futsal klaten",
    "booking lapangan klaten online",
    "harga lapangan per jam klaten",
    "tempat sewa lapangan murah klaten",
    "lapangan mini soccer di klaten",
  ],
  openGraphImage: "/og-sewa-lapangan-mini-soccer-klaten.jpg",
  logoImage: "/logo-sewa-lapangan-mini-soccer-klaten.png",
  phone: "+62 857 744 40016",
  email: "admin@dev.klatenminisoccer.web.id",
  instagram: "https://www.instagram.com/kim.soccerfield/",
  address: "Jl. Desan Karanganom, Karanganom, Kec. Klaten Utara, Kabupaten Klaten, Jawa Tengah 57438",
  hours: "06.00–23.00 Setiap hari",
  navItems: [
    { href: "/", label: "Beranda" },
    { href: "/book", label: "Booking Lapangan" },
    { href: "/booking-history", label: "Riwayat" },
  ],
};
