export const siteConfig = {
  name: "Klaten International Minisoccer",
  title: "Klaten International Minisoccer | Sewa Lapangan Mini Soccer Klaten",
  description:
    "Selamat datang di Klaten International Minisoccer, satu-satunya dan terbaik di Klaten! Booking online Rp 214.000–750.000, buka 06.00–23.00 setiap hari.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://klatenminisoccer.web.id",
  locale: "id_ID",
  keywords: [
    "kim minisoccer",
    "kim soccerfield",
    "kim soccerfield klaten",
    "lapangan bola kim klaten",
    "lapangan bola klaten",
    "kim klaten",
    "soccerfield klaten",
    "klaten international minisoccer",
    "lapangan di klaten",
    "sewa lapangan klaten",
    "booking lapangan klaten",
    "lapangan mini soccer klaten",
    "mini soccer klaten",
    "futsal klaten",
    "sewa lapangan mini soccer klaten",
    "lapangan klaten utara",
    "sewa lapangan klaten per jam",
    "tempat sewa lapangan klaten",
    "lapangan futsal klaten",
    "booking lapangan klaten online",
    "harga lapangan per jam klaten",
    "tempat sewa lapangan murah klaten",
    "lapangan mini soccer di klaten",
    "kim klaten utara",
    "karanganom minisoccer",
    "minisoccer karanganom",
    "satu-satunya minisoccer klaten",
    "rental lapangan klaten",
    "tarif lapangan klaten",
    "lapangan 5v5 klaten",
    "mini soccer 5v5 klaten",
    "mabar klaten",
    "sparing futsal klaten",
    "turnamen mini soccer klaten",
    "event futsal klaten",
    "lapangan bola malam klaten",
    "futsal malam klaten",
    "komunitas mini soccer klaten",
    "komunitas futsal klaten",
    "sewa lapangan murah klaten",
    "lapangan sepak bola mini klaten",
    "soccer field klaten",
    "booking online minisoccer klaten",
    "sewa lapangan klaten utara per jam",
  ],
  openGraphImage: "/og-sewa-lapangan-mini-soccer-klaten.jpg",
  logoImage: "/logo-sewa-lapangan-mini-soccer-klaten.png",
  phone: "+62 857 744 40016",
  email: "admin@dev.klatenminisoccer.web.id",
  instagram: "https://www.instagram.com/kim.soccerfield/",
  address: "Jl. Desan Karanganom, Karanganom, Kec. Klaten Utara, Kabupaten Klaten, Jawa Tengah 57438",
  hours: "06.00–23.00 Setiap hari",
  navItems: [
    { href: "/", label: "Beranda" },
    { href: "/book", label: "Booking Lapangan" },
    { href: "/booking-history", label: "Riwayat" },
  ],
};
